### ISSUE TITLE
Parsing error when # for comments are used in German language

### ISSUE THREAD

**Issue by heisee** [QuBiT/cucumber-netbeans-plugin#11]
http://wiki.github.com/aslakhellesoy/cucumber/gherkin
says:
"""
Comment lines are allowed anywhere in the file. They begin with zero or more spaces, followed by a sharp sign (#) and some amount of text.
"""

It seems like this features doesn't work in the new version 1.2.8 when language is set to "de". 
If I set it to "en", commented line parsing works fine.

thanks, heisee

**Comment by QuBiT** [comment]
fixed, just download it from download section again

(just missed one token) _argh_

**Comment by heisee** [comment]
yeah, very cool

thanks, heisee
