### ISSUE TITLE
Installing in NB for Ruby does install all the java development plugins

### ISSUE THREAD

**Issue by Knack** [QuBiT/cucumber-netbeans-plugin#12]
Hi. I've just installed the plugin in my "ruby only" Netbeans (6.7.1). After the installation, the following message is shown:

```
The NetBeans IDE Installer has successfully installed the following plugins:

Ant 
Java Source to Ant Bindings 
Javac Implementation Wrapper 
Java Lexer 
Java Project Support 
Javac API Wrapper 
Preprocessor Bridge 
Java Source 
Internationalization 
Java Platform 
Ant-Based Project Support 
Cucumber Features 
Java Support APIs 
```

I have no idea about NB plugin development, but I suppose all those dependencies are not really needed.

Hope I'll help.

**Comment by Knack** [comment]
**UPDATE: After restarting the IDE, it remains as a "ruby-only" IDE, eg. the Java plugins seems not to be installed, and only one new plugin is installed: Cucumber Features. Maybe the final message was wrong**

**Comment by QuBiT** [comment]
Nice to know, but this is just a NetBeans Issue and not a "my-module" issue ^^.

As this module uses java code inside for some features, it maybe that the ruby-only version has not included some special libraries for modules which use java and many more small features.

So, fine to know, but what should I do, when NetBeans does something like this ^^.

As long as it works ^^.
