### ISSUE TITLE
Feature Request: Right click on feature to run only that feature

### ISSUE THREAD

**Issue by tmilker** [QuBiT/cucumber-netbeans-plugin#13]
It would be nice if we could right click on either the .feature file in the Files tab or in the Features Navigator to run just that feature with "cucumber features/path/to/new.feature -s".  Adding a keybinding to run the currently opened and focused .feature file would also be convenient.

**Comment by QuBiT** [comment]
nice idea, maybe I'll do it, as soon as I find some time for it ;)

**Comment by QuBiT** [comment]
Since Version 1.6.5 this is now possible.

You can run your features by
- right click on the file
- right click inside the editor
- by pressing the new button inside your toolbar (you'll find it very easily)

**Comment by jorahood** [comment]
When I do this I get an exception on Mac OS X: 

java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:53)
    at java.lang.ProcessImpl.start(ProcessImpl.java:91)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)
Caused: java.io.IOException: Cannot run program "cmd": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:459)
    at qubit.cucumber.editor.threads.FeatureThread.run(FeatureThread.java:79)
[catch] at java.lang.Thread.run(Thread.java:637)

Seems that it is looking for a "cmd" exe, which would only work on Windows.

**Comment by QuBiT** [comment]
thats currently true, as I implemented it only for Windows at the moment.
I will look into this and add the support for OS X and Linux.

**Comment by QuBiT** [comment]
I've removed the cmd /C part of the command for non-windows systems and committed these changes.
As soon as we know what exactly your table indentation problem is (please check the issue), and we then solved it (if there is one), I'll upload a new version which enables this new functionality.

Cheers

(As the output of Cucumber is redirected to the Output-View of Netbeans, there is currently no coloring (just plain text).)
