### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by jsuchal** [QuBiT/cucumber-netbeans-plugin#14]
Hi,

i would be nice to be able to install this plugin without too many dependencies. I don't really know why do you need these:

Ant [3.35.1.2] Internationalization [1.26.1] Java Lexer [1.5.1] Java Platform [1.12.1] Java Project Support [1.25.2] Java Source to Ant Bindings [1.3.2.1.7] Java Source [0.44.2.7.8.1] Java Support APIs [1.19.1] Javac API Wrapper [0.8.1.1] Javac Implementation Wrapper [0.10.2.8] Preprocessor Bridge [1.7.1.1]

I am using netbeans 6.7.1 (only the ruby version).

Thanks.

**Comment by QuBiT** [comment]
same as Issue-12.

NetBeans requires them to use this Module, but my Module does NOT need them, the ruby-version simply does not have them to support modules correctly.

I did not add this modules directly as dependencies.

**Comment by jsuchal** [comment]
Ahh, sorry for that.

**Comment by QuBiT** [comment]
no problem

should I be wrong, let me know.
