### ISSUE TITLE
How do you run the feature within Netbeans

### ISSUE THREAD

**Issue by Jimflip** [QuBiT/cucumber-netbeans-plugin#17]
I'm probably being a bit dumb, but how do you run a test from within Netbeans?

**Comment by QuBiT** [comment]
Hi,

there are no dumb questions, there are only dumb answers ;-)

Currently there is no direct way to run your .feature file inside NetBeans and below you see why:

There is a quit good way to run your tests provided by cucumber itself:

using the rake task "cucumber" and tags ( http://wiki.github.com/aslakhellesoy/cucumber/tags )

just use the @wip tag for example in your feature file and run "rake cucumber:wip" to run your "work in progress"-features ... and so on ...

as your tests may also be executed on a separate machine (pc/server/...) this module/plugin is only intended to help you to write those feature-files.

but if you have the time and the knowledge to implement it to run it from inside NetBeans, then feel free to "fork" this project and aftwards I'll pull your code into this project.

**Comment by QuBiT** [comment]
Since Version 1.6.5 you can now run files from within Netbeans.

You can run your features by

```
* right click on the file
* right click inside the editor
* by pressing the new button inside your toolbar (you'll find it very easily)
```
