### ISSUE TITLE
Feature request: auto format for tables

### ISSUE THREAD

**Issue by fgalli** [QuBiT/cucumber-netbeans-plugin#18]
Hi, I saw from a webcast a nice feature from another editor. The ability to autoformat tables like this:

| name | price |
| Milk | 2.99 |
| Puzzle | 8.99 |

Into a nicer way like (hope it doesn't mess up the spaces...btw it's all aligned):

| name   | price |
| Milk   | 2.99  |
| Puzzle | 8.99  |

I really hope to see this little feature added to this great nb module

**Comment by fgalli** [comment]
It messed up... this is the correct one: http://pastebin.com/f43c84938

**Comment by kbaum** [comment]
I agree.  It would be great if we could autoformat tables in netbeans.

**Comment by aslakhellesoy** [comment]
Here is how TextMate does it: http://github.com/bmabey/cucumber-tmbundle/blob/master/Support/lib/cucumber/mate/table_aligner.rb#L34

(Watch out for UTF-8).

Should be easy to port to Java.

**Comment by aslakhellesoy** [comment]
You may also want to take a look at a java implementation for aligning tables, in Gherkin:

http://github.com/aslakhellesoy/gherkin/blob/master/java/src/gherkin/formatter/PrettyFormatter.java

Thinking about it - maybe you could use the entire formatter to format the entire feature of the current editor! See the main class for an example:

http://github.com/aslakhellesoy/gherkin/blob/master/java/src/gherkin/Main.java

**Comment by aslakhellesoy** [comment]
I have now made binary releases (jar) of Gherkin available in this Maven repo: http://cukes.info/maven

This should give you what you need to start using Gherkin's autoformat. Again - see the Main class. It has moved to http://github.com/aslakhellesoy/gherkin/blob/master/java/src/main/java/gherkin/Main.java

**Comment by aslakhellesoy** [comment]
If you find any bugs in the PrettyFormatter, please file a bug in the Gherkin project, adding a link to a gist with a feature that isn't properly reformatted.

**Comment by QuBiT** [comment]
Thanks to Aslak, the new Version 1.6.5 is ready for download, so try it out.

To Format a File you have 2 possibilities:
- right click inside the editor and select "Format"

or
- press ALT-SHIFT-F

**Comment by jorahood** [comment]
Just wanted to note that for me, formatting does not normalize the widths of tables. Was this an intended outcome?

**Comment by aslakhellesoy** [comment]
Tables should be formatted too. Can you paste your feature to http://gist.github.com and give us a link? I'll look into it.

**Comment by QuBiT** [comment]
Tested it with NetBeans 6.9M1 and NetBeans 6.8 with Version 1.6.7 and different Features (en, de) and all worked well.

Did you upgrade from a Version below 1.6.5?
yes -> check if there are two modules installed, uninstall the old one.
yes, and I uninstalled it, and I still get this error -> if you can try to delete your .netbeans/<version> folder, "maybe" this helps.

**Comment by jorahood** [comment]
Must have been a pbkm, works fine now. Kudos!
