### ISSUE TITLE
Support * as synonym for Given, When, Then, And

### ISSUE THREAD

**Issue by jorahood** [QuBiT/cucumber-netbeans-plugin#19]
This was added to cucumber recently, it would be nice to be able to use in Netbeans.

**Comment by QuBiT** [comment]
Hi,

thanks for the info.
I've checked this and you are right.
So I've added it and released version 1.3.1 (available in the download section).

please download it and try it and write back if something does not work as supposed to.

Cheers

**Comment by jorahood** [comment]
Got it, looks great, thank you for such a quick response!
