### ISSUE TITLE
Generic Language Framework version 

### ISSUE THREAD

**Issue by henry74** [QuBiT/cucumber-netbeans-plugin#2]
I'm getting the following error when attempting to install:

Some plugins require plugin Generic Languages Framework to be installed.
The plugin Generic Languages Framework is requested in version >= 1.93.1.2 but only 1.92.0.1 was found.  The following plugin is affected: Cucumber Features 

I'm running Netbeans 7.0M1.  I'm looking for the plugin "Generic Languages Framework" but wasn't able to find it in order to update it  Thoughts appreciated.

**Comment by QuBiT** [comment]
Hi, thanks for your post.
Currently I used NetBeans 6.7 RC2, and made some changes, and NetBeans updated the Requirements to 6.7 RC2.

I changed them all back, so it is compatible with NetBeans >= 6.5.1

Please download it and install it again.
