### ISSUE TITLE
feature request: support Toggle Comment

### ISSUE THREAD

**Issue by jorahood** [QuBiT/cucumber-netbeans-plugin#20]
This would be very helpful for commenting out several lines at once and then uncommenting them. Obviously I have no idea how difficult it is, but if it's easy it would be great to have.

**Comment by QuBiT** [comment]
Hi,

this would be definitely a great addition to this module. (even if I never missed that feature ^^ for cucumber, see at the bottom why)

Currently "CTRL-SHIFT-C" does not work, as there is a lack of documentation on the Schliemann project on how hotkeys/shortcuts or anything like that should be implemented. I've read through several other examples which implement a different language, but none of them has this support. If I am wrong, send me the .nbm and I'll dig into this module and extract that code if possible.

my solution (workaround, or why I've never missed it) is/was to use tags (this does not apply to lines, but to features and scenarios):

when you run "rake cucumber:wip" only those scenarios (features) are executed, which have this tag, hence "rake cucumber" ignores them.
So I suggest to write your own rake task for the @ignore tag (copy and modify cucumber:wip and add @ignore in the same way to "rake cucumber" as @wip.was designed.

hope this is useful for you at the moment.

if there is a way to implement it "as it was supposed", I'll do it and let you know.

Cheers

this is how your cucumber.yml in the config folder could look like:

<pre>
<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format progress features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "-r features #{rerun_opts} --format rerun --out rerun.txt --strict --tags ~@wip ~@ignore"
%>
default: <%= std_opts %>
ignore: --tags @ignore:3 --ignore features
wip: --tags @wip:3 --wip features
</pre>

**Comment by QuBiT** [comment]
Since Version 1.4.0 this is now possible. (CTRL-SHIFT-C ... default editor command in netbeans)

Cheers
Roland
