### ISSUE TITLE
unexpected token, english, any colon in a step definition

### ISSUE THREAD

**Issue by dyoung** [QuBiT/cucumber-netbeans-plugin#23]
Tried to pass a Ruby label as a parameter. Got an "unexpected token" error in the IDE because of the colon in the label's name--the same code works if I pass a string.  

Cucumber does not return an error.

**Comment by dyoung** [comment]
Should have mentioned: I also get an "unexpected token" on all subsequent lines. Makes use of feature files w/in the IDE impractical 'cause of all the red squigglies. 

Additional info:

Product Version: NetBeans IDE 6.8 (Build 200912041610)
Java: 1.6.0_13; Java HotSpot(TM) 64-Bit Server VM 11.3-b02
System: Linux version 2.6.28-11-generic running on amd64; UTF-8; en_US (nb)
Userdir: /home/vlad/.netbeans/6.8

**Comment by QuBiT** [comment]
Hi,

please post your feature file at http://gist.github.com/ and send me that link so that I can reproduce your error.

I'll check it then.

Cheers

QuBiT

**Comment by dyoung** [comment]
Sorry--can't post actual files, as they're proprietary. But the error occurs, so far, in all step definitions that try to pass Ruby labels (or otherwise use a colon). If it isn't equally obvious on your machine, I doubt my file(s) would change anything.

**Comment by dyoung** [comment]
.

**Comment by QuBiT** [comment]
by "Ruby Labels" you mean "symbols" or what?

Currently it is getting late in the region of my timezone and I am tired, so please be more specific and provide an "unproprietary" example feature file.

just replace the "highly gifted business value" with some "bla bla" and post it as requested.

I really want to help you, but I need more information.

Cheers

**Comment by QuBiT** [comment]
As you closed the issue I hope that you have resolved your problem and there is no module problem.

If I am wrong, or
if there is anything else you want to have improved, implemented, ... just let me know.

Cheers
QuBiT
