### ISSUE TITLE
Netbeans does not runs cucumber from the RAILS_PATH path 

### ISSUE THREAD

**Issue by emoreth** [QuBiT/cucumber-netbeans-plugin#26]
Netbeans seems to be running cucumber command from the folder above the rails project folder.

Output of running [cucumber, /home/myuser/www/rails/myproject/features/authentication.feature, -p, default] is:
--- START ---

cucumber.yml was not found.  Please refer to cucumber's documentation on defining profiles in cucumber.yml.  You must define a 'default' profile to use the cucumber command without any arguments.
Type 'cucumber --help' for usage.
--- END ---

Adding on env.rb:
puts "CURRENT DIR: #{Dir.pwd}"

Returns me => CURRENT DIR: /home/myuser/www/rails/
And not /home/myuser/www/rails/myproject

Regards

**Comment by QuBiT** [comment]
have you tried to use the -r option from the options dialog? (the Recursive Check Box)

**Comment by emoreth** [comment]
Yes, no difference.

**Comment by QuBiT** [comment]
Hi again,

I've tested it and yes this error occurs when you use the "-p default". When you leave it away, it works, as you are right, it only uses the cucumber.yml file if it is available in the current directory.

I will look into it and try to solve that issue

Cheers,
QuBiT

**Comment by emoreth** [comment]
I found something REALLY weird!

I'm developing a new system using a opensource framework on git, that we could call HHH.

My Rails folder, used to run all rails application is: /home/emoreth/www/rails

From this project I downloaded, lets say I put in a folder called OOO (Note that H comes before O).

My folder tree is:

home/emoreth/www/rails/
home/emoreth/www/rails/HHH << GIT Folder
home/emoreth/www/rails/OOO << NB Folder

Then netbeans looks for the files on HHH instead of OOO!

But if I rename HHH to ZZZ, now note that O comes before Z,
Then my tree folder is :

home/emoreth/www/rails/
home/emoreth/www/rails/OOO << NB Folder
home/emoreth/www/rails/ZZZ << GIT Folder

Netbeans now look for the folders on the right place: OOO.

That's not all! If i move ZZZ to /home/emoreth/Desktop
Note that D (Desktop) comes before w (www)
And the tree is:

home/emoreth/Desktop/ZZZ << GIT Folder
home/emoreth/www/rails/
home/emoreth/www/rails/OOO << NB Folder

It still looks into the ZZZ folder, wich means the it is probably looking for the first rails app it finds on my whole disk!!

This could explain that delay before starting each instance...

Please take a look into it!

Regards,
Emoreth

**Comment by QuBiT** [comment]
Thanks for your detailed description,

the problem was solved meanwhile by setting the working directory for the process, which was not set before, hence the execution was not able to find your cucumber.yml file and also was not done in the correct directory (which is not a problem, if you do not need to access the cucumber.yml file.)

Please download the new Version 1.8.1 from the Download section. For more details please checkout the wiki page:

http://wiki.github.com/QuBiT/cucumber-netbeans-plugin/code-execution

I have tested it with Windows and Ubuntu. Please let me know if something is still broken, or missing.

If it is solved, please comment and close that Issue.

Cheers Roland

**Comment by emoreth** [comment]
Still did'nt realize how to update to this one. But anyway, in my opinion it should be only a tmp fix for this problem once that cucumber should always run from the project path and it is not set on a project basis, wich means we need to change it every time we change project.

Regards,
Emoreth

**Comment by emoreth** [comment]
Updated and now it works!

Thanks and keep improving it!
