### ISSUE TITLE
French plugin : order of elements in feature description too strict

### ISSUE THREAD

**Issue by ukabu** [QuBiT/cucumber-netbeans-plugin#3]
The order if the elements in the Feature (Fonctionnalité) description is way too strict. I would prefer for the plugin to only highlight the specific keyword (Afin de gagner) instead of requiring that they appear in a specific order. Also, they should not be mandatory.

**Comment by QuBiT** [comment]
In Version 1.2.2 this elements are no longer mandatory, but the order is still fixed.
The reason for mandatory was that, you should define your BusinessValue, Role and the SomeAction you take to reach your BusinessValue to focus in your development on what is really needed.

**Comment by ukabu** [comment]
I would prefer to not have anything mandatory (order, presence of keyword). I would'nt mind if a warning hint is displayed if something is missing or in the wrong order, but cumcumber is about describing features in text in a way that a business user can do it. I feel that only errors that would prevent Cucumber to correctly parse the feature files should raise errors.

Anything else should be raised as warnings.

**Comment by QuBiT** [comment]
the order is no longer fixed in version 1.2.3, also a new French version is available
