### ISSUE TITLE
French plugin : "En tant que" should also match on "En tant qu'"

### ISSUE THREAD

**Issue by ukabu** [QuBiT/cucumber-netbeans-plugin#4]
In french, if `que` is followed by a vowel, we write `qu'`.

For instance, we do not write :
En tant que un utilisateur
We write
En tant qu'un utilisateur

The plugin does not match the variation with the single quote.

**Comment by QuBiT** [comment]
Please read the Language Support in the README file (http://github.com/QuBiT/cucumber-netbeans-plugin) and send me the required list and file so that I can include all possible keywords.

**Comment by ukabu** [comment]
You can most of them with "cucumber --language fr help"

In French :

Feature     -> Fonctionnalité

In order to -> Afin de

As a -> En tant que, En tant qu'

I want to   -> Je désire, Je veux, Je souhaite

Scenario    -> Scénario

Scenario Outline -> Plan du Scénario

Given -> Soit

When -> Lorsque

Then -> Alors

And     -> Et

Examples -> Exemples

Background -> Contexte

**Comment by QuBiT** [comment]
thx, I also found http://github.com/aslakhellesoy/cucumber/blob/master/lib/cucumber/languages.yml where all translations are given. I will update the README soon.

**Comment by QuBiT** [comment]
New FRENCH Version released is released.
