### ISSUE TITLE
French plugin: "Contexte:" yield an unexpected token ":" error

### ISSUE THREAD

**Issue by ukabu** [QuBiT/cucumber-netbeans-plugin#5]
I have a feature with a "Contexte:" section (Scénario background).

I get an unexpected token ":" for the colon in the line...

<pre>
Contexte:
    Lorsque je suis authentifié sur le site
</pre>

**Comment by QuBiT** [comment]
Please read the Language Support in the README file (http://github.com/QuBiT/cucumber-netbeans-plugin) and send me the list required list and file so that I can include all possible keywords.

**Comment by QuBiT** [comment]
Additional:

Lorque (When) should not be used in the Background. In the Background you should only define what is given (because there is no conditional sense in Background) and then in your Scenario you should do the test "When -> Then" (based also on the Given from the Background.

**Comment by ukabu** [comment]
When I refactor my common steps from Scenarios into a Background, I get lazy and do not rename the first keyword. Also, I thing that the plugin should not report errors for things that cucumber does not report error on.

**Comment by QuBiT** [comment]
Problem solved and new FRENCH Version released.
