### ISSUE TITLE
Frech plugin should be merge in main plugin and support multilanguage setups.

### ISSUE THREAD

**Issue by ukabu** [QuBiT/cucumber-netbeans-plugin#6]
I have some projects that uses english features, some other that uses french features.

It would be nice if I could specify the feature language on a project per project basis... And even better support the new language per feature file feature of cucumber.

**Comment by QuBiT** [comment]
nice idea, but it is not so easy as you might think.
you have to change the parser which is loaded with the module, and therefore it is not possible to do this on the fly.
if I find a solution for this, then this would be great but currently this is not doable.

**Comment by ukabu** [comment]
Maybe, an alternative solution, would be to match the parser with the file extension. Like *_fr.feature or *.fr.feature. The default *.feature extension could always be in English.
I could live with renaming my feature files to get multilanguage support.

**Comment by QuBiT** [comment]
I will try this solution, as this one was also in my mind, but I am not sure if NetBeans can handle this.
